=== TasnadiAttila/AdvancedXML/xml/7/7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="characters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="character"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="character">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="titles"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="titles">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
</xs:schema>

=== TasnadiAttila/AdvancedXML/xml/7/7.xml
<?xml version="1.0" encoding="UTF-8"?>
<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="7.xsd">
    <character>
        <name>Balon Greyjoy</name>
        <titles>
            <title>Iron King</title>
            <title>King of the Isles and the North</title>
            <title>King of Salt and Rock</title>
            <title>Son of the Sea Wind</title>
            <title>Lord Reaper of Pyke</title>
            <title>The Greyjoy</title>
            <title>Captain of the Great Kraken</title>
        </titles>
    </character>
    <character>
        <name>Chayle</name>
        <titles>
            <title>Septon</title>
        </titles>
    </character>
    <character>
        <name>Gillam</name>
        <titles>
            <title>Brother</title>
        </titles>
    </character>
    <character>
        <name>High Septon</name>
        <titles>
            <title>High Septon</title>
            <title>His High Holiness</title>
            <title>Father of the Faithful</title>
            <title>Voice of the Seven on Earth</title>
        </titles>
    </character>
    <character>
        <name>Margaery Tyrell</name>
        <titles>
            <title>Queen of the Seven Kingdoms</title>
        </titles>
    </character>
    <character>
        <name>Melicent</name>
        <titles>
            <title>Septa</title>
        </titles>
    </character>
    <character>
        <name>Meribald</name>
        <titles>
            <title>Septon</title>
        </titles>
    </character>
    <character>
        <name>Moelle</name>
        <titles>
            <title>Septa</title>
        </titles>
    </character>
    <character>
        <name>Mordane</name>
        <titles>
            <title>Septa</title>
        </titles>
    </character>
    <character>
        <name>Nysterica</name>
        <titles>
            <title>Septa</title>
        </titles>
    </character>
    <character>
        <name>Ollidor</name>
        <titles>
            <title>Septon</title>
        </titles>
    </character>
    <character>
        <name>Osmynd</name>
        <titles>
            <title>Septon</title>
        </titles>
    </character>
    <character>
        <name>Raynard</name>
        <titles>
            <title>Septon</title>
        </titles>
    </character>
    <character>
        <name>Scolera</name>
        <titles>
            <title>Septa</title>
        </titles>
    </character>
    <character>
        <name>Torbert</name>
        <titles>
            <title>Septon</title>
        </titles>
    </character>
    <character>
        <name>Tywin Lannister</name>
        <titles>
            <title>Lord of Casterly Rock</title>
            <title>Shield of Lannisport</title>
            <title>Warden of the West</title>
            <title>Hand of the King</title>
            <title>Savior of the City (of King's Landing)</title>
        </titles>
    </character>
    <character>
        <name>Unella</name>
        <titles>
            <title>Septa</title>
        </titles>
    </character>
    <character>
        <name>Abelar Hightower</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Addam Frey</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Addam Marbrand</name>
        <titles>
            <title>Ser</title>
            <title>Commander of the City Watch</title>
        </titles>
    </character>
    <character>
        <name>Addam Velaryon</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Addison Hill</name>
        <titles>
            <title>Ser</title>
            <title>Lord Commander of the Kingsguard</title>
        </titles>
    </character>
    <character>
        <name>Aegon I</name>
        <titles>
            <title>King of All Westeros</title>
            <title>Shield of His People</title>
            <title>King of the Andals, the Rhoynar and the First Men</title>
            <title>Lord of the Seven Kingdoms</title>
            <title>Protector of the Realm</title>
            <title>Lord of Dragonstone</title>
        </titles>
    </character>
    <character>
        <name>Aegon II</name>
        <titles>
            <title>King of the Andals, the Rhoynar and the First Men</title>
            <title>Lord of the Seven Kingdoms</title>
            <title>Protector of the Realm</title>
        </titles>
    </character>
    <character>
        <name>Aegon III</name>
        <titles>
            <title>King of the Andals, the Rhoynar and the First Men</title>
            <title>Lord of the Seven Kingdoms</title>
            <title>Protector of the Realm</title>
        </titles>
    </character>
    <character>
        <name>Aegon IV</name>
        <titles>
            <title>King of the Andals, the Rhoynar and the First Men</title>
            <title>Lord of the Seven Kingdoms</title>
            <title>Protector of the Realm</title>
        </titles>
    </character>
    <character>
        <name>Aegon Targaryen</name>
        <titles>
            <title>Prince</title>
        </titles>
    </character>
    <character>
        <name>Aegon Targaryen</name>
        <titles>
            <title>Prince</title>
        </titles>
    </character>
    <character>
        <name>Aegon Targaryen</name>
        <titles>
            <title>Prince</title>
        </titles>
    </character>
    <character>
        <name>Aegon V</name>
        <titles>
            <title>King of the Andals, the Rhoynar and the First Men</title>
            <title>Lord of the Seven Kingdoms</title>
            <title>Protector of the Realm</title>
        </titles>
    </character>
    <character>
        <name>Aegor Rivers</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Aelinor Penrose</name>
        <titles>
            <title>Queen</title>
        </titles>
    </character>
    <character>
        <name>Aemma Arryn</name>
        <titles>
            <title>Queen</title>
        </titles>
    </character>
    <character>
        <name>Aemon Estermont</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Aemon Rivers</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Aemon Targaryen</name>
        <titles>
            <title>Maester</title>
        </titles>
    </character>
    <character>
        <name>Aemond Targaryen</name>
        <titles>
            <title>Prince</title>
            <title>Protector of the Realm</title>
            <title>Prince Regent</title>
        </titles>
    </character>
    <character>
        <name>Aenys Frey</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Aenys I</name>
        <titles>
            <title>King of the Andals, the Rhoynar and the First Men</title>
            <title>Lord of the Seven Kingdoms</title>
            <title>Protector of the Realm</title>
        </titles>
    </character>
    <character>
        <name>Aerion Targaryen</name>
        <titles>
            <title>Prince</title>
        </titles>
    </character>
    <character>
        <name>Aerion Targaryen</name>
        <titles>
            <title>Lord of Dragonstone</title>
        </titles>
    </character>
    <character>
        <name>Aeron Greyjoy</name>
        <titles>
            <title>Priest of the Drowned God</title>
            <title>Captain of the Golden Storm (formerly)</title>
        </titles>
    </character>
    <character>
        <name>Aerys I</name>
        <titles>
            <title>King of the Andals, the Rhoynar, and the First Men</title>
            <title>Lord of the Seven Kingdoms</title>
            <title>Protector of the Realm</title>
        </titles>
    </character>
    <character>
        <name>Aerys II</name>
        <titles>
            <title>King of the Andals, the Rhoynar and the First Men</title>
            <title>Lord of the Seven Kingdoms</title>
            <title>Protector of the Realm</title>
        </titles>
    </character>
    <character>
        <name>Aglantine</name>
        <titles>
            <title>Septa</title>
        </titles>
    </character>
    <character>
        <name>Aladale Wynch</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Alannys Harlaw</name>
        <titles>
            <title>Queen of the Iron Islands</title>
        </titles>
    </character>
    <character>
        <name>Albar Royce</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Alekyne Florent</name>
        <titles>
            <title>Lord of Brightwater (attainted)</title>
        </titles>
    </character>
    <character>
        <name>Alerie Hightower</name>
        <titles>
            <title>Lady of Highgarden</title>
        </titles>
    </character>
    <character>
        <name>Alesander Staedmon</name>
        <titles>
            <title>Lord of Broad Arch</title>
        </titles>
    </character>
    <character>
        <name>Alester Florent</name>
        <titles>
            <title>Lord of Brightwater</title>
            <title>Hand of the King</title>
        </titles>
    </character>
    <character>
        <name>Alester Tyrell</name>
        <titles>
            <title>Ser</title>
        </titles>
    </character>
    <character>
        <name>Alicent Hightower</name>
        <titles>
            <title>Lady</title>
            <title>Queen</title>
            <title>Dowager Queen</title>
        </titles>
    </character>
    <character>
        <name>Alliser Thorne</name>
        <titles>
